# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy scraping app

on:
  workflow_dispatch:

  schedule:
    - cron: '2 18 * * *'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: |
          node index.js
          git config user.name Be4gu
          git config user.email Be4gu@gmail.com
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update times database"
          git push origin main
